---
kind: pipeline
type: exec
name: Deploy to Prod

steps:
- name: Copying Files
  commands:
  - echo $DRONE_WORKSPACE
  - cp -r $DRONE_WORKSPACE/* /opt/docker_home/trine/html

trigger:
  branch:
    - main
  event:
    - push